name: ListenSDR

options:
  minimumXcodeGenVersion: 2.38.0

targets:
  ListenSDR:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: ListenSDR/Sources
      - path: ListenSDR/Resources
    info:
      path: ListenSDR/Info.plist
      properties:
        CFBundleDisplayName: Listen SDR
        CFBundleShortVersionString: "1.0.1"
        CFBundleVersion: "89"
        ITSAppUsesNonExemptEncryption: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIBackgroundModes:
          - audio
        UILaunchScreen: {}
        UIRequiresFullScreen: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kazek.sdr
        CURRENT_PROJECT_VERSION: 89
        MARKETING_VERSION: 1.0.1
        SWIFT_VERSION: 5.10
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: ListenSDR/ListenSDR.entitlements
  ListenSDRTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: ListenSDRTests
    dependencies:
      - target: ListenSDR
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.kazek.sdr.tests
        SWIFT_VERSION: 5.10
