import ListenSDRCore

typealias KiwiWaterfallRate = ListenSDRCore.KiwiWaterfallRate
typealias KiwiWaterfallWindowFunction = ListenSDRCore.KiwiWaterfallWindowFunction
typealias KiwiWaterfallInterpolation = ListenSDRCore.KiwiWaterfallInterpolation
